name: dreamhunter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flame: ^1.35.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bonfire: ^3.16.1
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  http: ^1.6.0
  flame_tiled: ^1.21.2
  firebase_auth: ^6.1.4
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Free/
    - assets/widget/


